# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gql.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gql.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userfriend',
            unique_together=set([('user_1', 'user_2')]),
        ),
        migrations.AlterUniqueTogether(
            name='userevent',
            unique_together=set([('user', 'event')]),
        ),
    ]
